name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # You can change to any version like '7.4', '8.0', etc.

    - name: List project files
      run: ls -la

    # Add your custom build or deployment steps below
    # For example, if you want to deploy to a server using rsync/ftp/scp/etc.
    # or run simple PHP scripts, you can add them here.
